# Question 1
Write the program for deleting an element from the beginning and from any position.

In [11]:
#deletion from sarting

import numpy as np
a=np.array([10,20,70,2,4,6,45])
for i in range(1,len(a)):
    a[i-1]=a[i]
a



array([20, 70,  2,  4,  6, 45, 45])

In [12]:
#deletion any position


import numpy as np
a=np.array([10,20,70,2,4,6,45])
p=int(input())
for i in range(p,len(a)):
    a[i-1]=a[i]
a


2


array([10, 70,  2,  4,  6, 45, 45])

# Question 2
Write the program for printing the array after rotating it k times towards left, where k
would be taken as user input.

In [21]:
b=np.array([10,20,70,2,4,6,45])
k=int(input())
for i in range(k):
    temp=b[0]
    for j in range(n-1):
        b[j]=b[j+1]
    b[n-1]=temp
b


2


array([70,  2,  4,  6, 45, 10, 20])